# Generated by Django 4.1.7 on 2023-03-09 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_notification_receiver_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
    ]
